#!/bin/bash

PARAMS=~/.efalive

print_help() {
    echo "Syntax: [-p] [<DIRECTORY>]"
}

if [ $1 ]
then
    if [ $2 ]
    then
        if [ "x$1" != "x-p" -o ! -d $2 ]
        then
            print_help
            exit 1
        fi
        PARAMS="-p $2"
    else
        if [ "x$1" = "x-p"  ]
        then
            PARAMS="-p $PARAMS"
        elif [ -d $1 ]
        then
            PARAMS="$1"
        else
            print_help
            exit 1
        fi
    fi
fi

#PYTHONPATH=./efalive:$PYTHONPATH
#PYTHONPATH=$PYTHONPATH
python3 /usr/lib/python3/dist-packages/efaLiveTools-3.0-py3.11.egg/efalivesetup.py $PARAMS >> /dev/null

