[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "efaLiveTools"
version = "3.0"
authors = [
    {name = "Kay Hannay", email = "klinux@hannay.de"},
]
description = "Tools for efaLive"
requires-python = ">=3.9"
license = "GPL-3.0-only"
dependencies = [
    "PyGObject>=3.50.0",
    "python-pam>=2.0.2",
    "pyudev>=0.24.3",
    "python-dateutil>=2.9.0",
    "lockfile>=0.12.2",
]

[project.optional-dependencies]
dev = [
    "coverage>=7.6.12",
    "pytest>=8.3.4",
]

[project.urls]
Homepage = "https://www.hannay.de/efalive"

[tool.setuptools.packages.find]
include = ["efalive*"]
