[tool.poetry]
name = "efalive"
version = "2.8.3"
description = ""
authors = ["Kay Hannay <klinux@hannay.de>"]

[tool.poetry.dependencies]
python = "^3.7"
pygobject = "^3.38.0"
python-pam = "^1.8.4"
pyudev = "^0.22.0"
python-dateutil = "^2.8.2"
lockfile = "^0.12.2"

[tool.poetry.dev-dependencies]
mock = "^4.0.3"
nose = "^1.3.7"
coverage = "^5.5"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
