#! /bin/sh
### BEGIN INIT INFO
# Provides:          efa
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:	     console-screen acpid dbus hal
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: EFA - Elektronisches Fahrtenbuch
# Description:       EFA ist ein elektronisches Fahrtenbuch 
#		     fuer Rudervereine.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/startx
PIDDIR=/var/run/efa
PIDFILE=$PIDDIR/efa.pid
NAME=efa
PROCESS=xinit
DAEMONUSER=efa
DESC="Elektronisches Fahrtenbuch"
DAEMON_OPTS="-- -br"

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

set -e

do_start() {
    x_running=`ps a | grep $PROCESS | grep -v grep | wc -l`
    if [ $x_running -eq 0 ]
    then
        /bin/su -l $DAEMONUSER -c "$DAEMON $DAEMON_OPTS" >> /dev/null 2>&1 &
    fi
}

do_stop() {
    x_running=`ps ax | grep $PROCESS | grep -v grep | wc -l`
    if [ $x_running -gt 0 ]
    then
        killall $PROCESS >> /dev/null 2>&1
    fi
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	log_end_msg $?
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	sleep 1
	do_start
	log_end_msg $?
	;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
