#!/bin/bash

DIR=~/.efalive

if [ $1 ]
then
    if [ -d $1 ]
    then
        DIR=$1
    else
        echo "Error, not a directory: $1"
	exit 1
    fi
fi

PYTHONPATH=.:$PYTHONPATH 
PYTHONPATH=$PYTHONPATH python -m efalivesetup.maingui $DIR >> /dev/null

