Document: efalive
Title: Debian efalive Manual
Author: <insert document author here>
Abstract: This manual describes what efalive is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/efalive/efalive.sgml.gz

Format: postscript
Files: /usr/share/doc/efalive/efalive.ps.gz

Format: text
Files: /usr/share/doc/efalive/efalive.text.gz

Format: HTML
Index: /usr/share/doc/efalive/html/index.html
Files: /usr/share/doc/efalive/html/*.html
