#!/bin/sh
# Change the autogenerated user password to "debianlive"

password="2rOBlGiZ0Ggiw" # as in $(echo "efa" | mkpasswd -s)
sed -i -e 's/\(user_crypted=\)\(.*\)\( #.*\)/\1\"'${password}'\"\3/' /usr/share/initramfs-tools/scripts/live-bottom/10adduser
update-initramfs -tu -kall

